// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroAeronaves.DAL;

#nullable disable

namespace RegistroAeronaves.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("RegistroAeronaves.Models.Aeronaves", b =>
                {
                    b.Property<int>("AeronavesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aerolinea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAeronave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("capacidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("AeronavesId");

                    b.ToTable("Aeronaves");
                });
#pragma warning restore 612, 618
        }
    }
}
